name: CI/CD

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    # - name: Run the tests and generate coverage report
    #   run: npm test -- --coverage

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

    - name: Cypress run
      uses: cypress-io/github-action@v2
      timeout-minutes: 10
      with:
        record: true
        parallel: true
        start: npm run cypress
        group: Parallel 2x on ${{ matrix.os }}.
      env:
        # pass the Dashboard record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


