name: build

on:
  push:
    paths-ignore:
      - '*.md'
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
      - name: install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: build app
        run: yarn build
